### ISSUE TITLE
LP detection weight

### ISSUE THREAD

**Issue by aivyon** [mrzaizai2k/License-Plate-Recognition-YOLOv7-and-CNN#1]
Hi. thank you for sharing!
Nice work
Can you provide the weights used for LP detection?
thank you!

**Comment by mrzaizai2k** [comment]
I remember I put them both yolo and cnn in releases of Github. You can
check.

**Comment by aivyon** [comment]
Thank you!!

**Comment by mrzaizai2k** [comment]
Pls check out my youtube channel. That's would be grate to me. Thanks

**Comment by aivyon** [comment]
Definitely!! Thanks a lot. Great job!
