### ISSUE TITLE
Function Rotate LP is not flexible

### ISSUE THREAD

**Issue by TruongNoDame** [mrzaizai2k/License-Plate-Recognition-YOLOv7-and-CNN#10]
I have referred to your license plate rotation code, however the code in function `rotate_LP`:
```
rotationMatrix = cv2.getRotationMatrix2D(ptPlateCenter, -angle, 1.0)
```
This code m -angle makes them only work if the license plate is tilted to the left. If license plates are tilted to the right, they don't work. However, when I remove the "-" sign from angle, it works normally. 

You should update your code in this case.

**Comment by mrzaizai2k** [comment]
Yah thank u, will fix it later
