### ISSUE TITLE
Can not install yaml~0.2.5. Too many errors in conv.py.

### ISSUE THREAD

**Issue by trung-nguyen-code** [mrzaizai2k/License-Plate-Recognition-YOLOv7-and-CNN#2]
The program said that it couldn't install yaml~0.2.5 when I tried to pip install -r requirements.txt.
Besides, when I ran main_video.py, it said that some errors happened in conv.py

**Comment by mrzaizai2k** [comment]
You can try different version of yaml. It usually error when you set up the
latesst vers
