### ISSUE TITLE
input folder missing

### ISSUE THREAD

**Issue by LarousseKhosravi** [mrzaizai2k/License-Plate-Recognition-YOLOv7-and-CNN#3]
Thank you for sharing the repo. The input folder is missing --> /input/vnlicenseplate/

**Comment by mrzaizai2k** [comment]
Yes it is. You have to create it yourself. A folder contains testing
images. Github doesnt allow me to upload that big data

**Comment by LarousseKhosravi** [comment]
Thank you so much for the reply. It is resolved now. I am closing the issue.

**Comment by mrzaizai2k** [comment]
You are welcome.
