### ISSUE TITLE
how to install and run program

### ISSUE THREAD

**Issue by ahictu** [mrzaizai2k/License-Plate-Recognition-YOLOv7-and-CNN#8]
I downloaded and ran it with python 3.11.4 and the error appeared ModuleNotFoundError: No module named 'cv2' and not install yaml~=0.2.5
I don't know where I went wrong. I hope you can guide me to start this program

**Comment by mrzaizai2k** [comment]
You has to downloaf all the necessary packages like opencv to your machine.
And usr the environment to use
